/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Orders.java
 *
 * Created on Apr 8, 2017, 8:10:31 PM
 */
package perros.Frames;

/**
 *
 * @author rahul
 */
public class Orders extends javax.swing.JInternalFrame {

    /*  GridBagLayout layout = new GridBagLayout();

    AddItem additempnl;
    AddPurchasal addpurchpnl;
     */
    public Orders() {
        initComponents();
    /*     additempnl = new AddItem();
    addpurchpnl = new AddPurchasal();
    DynamicPanel.setLayout(layout);
    GridBagConstraints gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    DynamicPanel.add(additempnl, gbc);
    gbc.gridx = 0;
    gbc.gridy = 0;
    DynamicPanel.add(addpurchpnl, gbc);

    additempnl.setVisible(false);
    addpurchpnl.setVisible(false);*/
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SelectOptionPanel = new javax.swing.JPanel();
        AddItemBtn = new javax.swing.JButton();
        AddPurchBtn = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 255));
        setPreferredSize(new java.awt.Dimension(1595, 800));

        SelectOptionPanel.setBackground(new java.awt.Color(51, 255, 255));
        SelectOptionPanel.setPreferredSize(new java.awt.Dimension(150, 600));

        AddItemBtn.setText("Add Inventory Item");
        AddItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemBtnActionPerformed(evt);
            }
        });

        AddPurchBtn.setText("Add Purchasals");
        AddPurchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPurchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectOptionPanelLayout = new javax.swing.GroupLayout(SelectOptionPanel);
        SelectOptionPanel.setLayout(SelectOptionPanelLayout);
        SelectOptionPanelLayout.setHorizontalGroup(
            SelectOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddItemBtn)
                    .addComponent(AddPurchBtn))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        SelectOptionPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {AddItemBtn, AddPurchBtn});

        SelectOptionPanelLayout.setVerticalGroup(
            SelectOptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectOptionPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(AddItemBtn)
                .addGap(18, 18, 18)
                .addComponent(AddPurchBtn)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        SelectOptionPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AddItemBtn, AddPurchBtn});

        getContentPane().add(SelectOptionPanel, java.awt.BorderLayout.LINE_START);

        DynamicPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        getContentPane().add(DynamicPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemBtnActionPerformed
        /*    additempnl.setVisible(true);
        addpurchpnl.setVisible(false); */     // TODO add your handling code here:
}//GEN-LAST:event_AddItemBtnActionPerformed

    private void AddPurchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPurchBtnActionPerformed
        /*  additempnl.setVisible(false);
        addpurchpnl.setVisible(true);   */     // TODO add your handling code here:
}//GEN-LAST:event_AddPurchBtnActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItemBtn;
    private javax.swing.JButton AddPurchBtn;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel SelectOptionPanel;
    // End of variables declaration//GEN-END:variables
}
